[package]
name = "gps_spoofing_detection"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# For GPS
adafruit_gps = "0.4.1"

# For MPU6050
rppal = "0.15.0"