block_labels = ["needs-decision"]
delete_merged_branches = true
required_approvals = 1
status = [
  "CI (stable, x86_64-unknown-linux-gnu)",
  "CI (stable, armv7-unknown-linux-gnueabihf)",
  "CI (1.46.0, x86_64-unknown-linux-gnu)",
]
