on:
  push:
    branches: [ staging, trying, master ]
  pull_request:

name: Continuous integration

jobs:
  ci-linux:
    name: CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # All generated code should be running on stable now
        rust: [stable]

        # The default target we're compiling on and for
        TARGET: [x86_64-unknown-linux-gnu, armv7-unknown-linux-gnueabihf]

        include:
          # Test MSRV
          - rust: 1.46.0
            TARGET: x86_64-unknown-linux-gnu

          # Test nightly but don't fail
          - rust: nightly
            experimental: true
            TARGET: x86_64-unknown-linux-gnu

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.TARGET }}
          override: true

      - name: Install armv7 libraries
        if: ${{ matrix.TARGET == 'armv7-unknown-linux-gnueabihf' }}
        run: sudo apt-get install -y libc6-armhf-cross libc6-dev-armhf-cross gcc-arm-linux-gnueabihf

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target=${{ matrix.TARGET }}

      - uses: actions-rs/cargo@v1
        if: ${{ matrix.TARGET == 'x86_64-unknown-linux-gnu' }}
        with:
          command: test
          args: --target=${{ matrix.TARGET }}
